### ISSUE TITLE
You should document SQK versions the various module versions work with.

### ISSUE THREAD

**Issue by chrishaff** [williamrijksen/com.williamrijksen.onesignal#10]
On Android 
- 1.3.0 appears to support 6.0(+) only.
- 1.1.0 appears to support SDK versions 5.

Didn't try the other versions.

**Comment by chmiiller** [comment]
If you go to Releases, the latest one is a release for both SDK versions and for me it's pretty clear that it supports both of them.
iOS version supports SDK 5 and 6. For Android there are 2 builds, one for 5.5.1 and other for 6.+
![versions](https://cloud.githubusercontent.com/assets/1013632/21292707/e848d4bc-c50d-11e6-97c8-6c0c8dab1f4b.png)

**Comment by chmiiller** [comment]
@williamrijksen I guess this one should be closed

**Comment by williamrijksen** [comment]
@chrishaff I'll close this issue.

**Comment by chrishaff** [comment]
Huh, learned something.  I was just going through the tagged versions, not "releases".  Thanks!
