### ISSUE TITLE
Unable to install using Appcelerator install method.  Manual install fails on Android compile.

### ISSUE THREAD

**Issue by chrishaff** [williamrijksen/com.williamrijksen.onesignal#11]
Installation using the wizard fails.  Asks about overwriting the archive though it's a clean install, then says the URL is not valid.
http://docs.appcelerator.com/platform/latest/#!/guide/Using_a_Module

Manual installation into the modules folder appears to work in Studio, but "module is not found" when compiled on Android 7 (Nexus 6P).

**Comment by chmiiller** [comment]
Never tried on Android 7 and don't have a phone to test it. Can you try to change the Android SDK folder, build the module and let us know if it works?

**Comment by williamrijksen** [comment]
@chrishaff Which release did you test? Take a look at: https://github.com/williamrijksen/com.williamrijksen.onesignal/releases/tag/1.3.0.

**Comment by chrishaff** [comment]
Works, thanks!

The trick (for me as a 5.5.1 user) was to use com.williamrijksen.onesignal-android-1.3.0-5.5.1.GA.zip.
