### ISSUE TITLE
Android: Module Conflicting with ti.map on Ti 6.0.1.GA

### ISSUE THREAD

**Issue by ygbr** [williamrijksen/com.williamrijksen.onesignal#14]
#Hi,

I'm trying the module version 1.3.0 on Ti SDK 6.0.1.GA but it is conflicting with vanilla ti.map.

When i try to build the app with the onesignal module I get the following error:

```
[ERROR] Conflicting jar files detected:
[ERROR]
[ERROR] The following modules have different "google-play-services-base.jar" files
[ERROR]    ti.map                         (version 3.0.1) (hash=730a1d6196847cb5b1067ac02a875876)
[ERROR]    com.williamrijksen.onesignal   (version 1.3.0) (hash=68b48e0a3cb3582bd4ab0bb00625b83a)
[ERROR]
[ERROR] You can either select a version of these modules where the conflicting jar file is the same or you
[ERROR] can try copying the jar file from one module's "lib" folder to the other module's "lib" folder.
```

I have tried to delete google-play-services-base.jar and the app compiles and dexes normally but when the app runs it gives a lot of errors regarding the google-play-services version.

Anybody managed to run this module together with ti.map on 6.0.1.GA successfully? If so what have you done regarding the conflicting google-play-services jars?

Thanks!

**Comment by chmiiller** [comment]
Hey Yg,
As seen here: https://github.com/Sitata/titanium-google-analytics/issues/48 seems that [Proguard](https://medium.com/all-titanium/deal-with-titanium-modules-and-its-missing-support-for-android-multidex-546de5486d13#.ae8edzb7c) is a solution, but I'm not a big fan of it. What do you think?

**Comment by ygbr** [comment]
Hi @chmiiller !
We have done the Proguard solution a few times in the past when we had to use Google Analytics modules together with Maps but it is kinda painful when you have to deal with a lot of Android modules and want to carry regular updates.

This has been a long living Titanium issue for Android modules and Axway haven't found a proper way to handle this yet... nor oriented module developers on how to manage this correctly... There are loads of issues related to those conflicts, multidex and android method limits on their JIRA...

That said, I will try to use stripped jars from https://jira.appcelerator.org/browse/TIMOB-19348 since they have done that for their modules and if it didn't work I will do it the Proguard way again.

Tks

**Comment by clem983** [comment]
Hi,
I have the same issue than you. Is there a solution to work with ti.map and onesignal together ?
Thanks a lot :)

**Comment by jvandijk** [comment]
@clem983 @ygbr Use version 3.0.0 of Ti.Map for now, that one matches on Google Play Services version.

**Comment by clem983** [comment]
That works, thanks a lot @jvandijk  :)

**Comment by williamrijksen** [comment]
Thanks @jvandijk! I'll close this issue.

**Comment by albwebbergate** [comment]
@jvandijk It works!!!!

ti.map 3.0.0
onesignal 1.3.0
sdk-version 6.0.2.GA
