### ISSUE TITLE
Implementation of getTags (Android)

### ISSUE THREAD

**Issue by aurusapps** [williamrijksen/com.williamrijksen.onesignal#15]
Hi,

Not sure how others are doing it, but its currently not possible to clear tags of a user without knowing which tags were set in the absence of getTags and deleteTags methods in the module.

A work around would be to maintain a property (like a cookie) in the app but this method is causing redundancy of data (tags are being maintained and referred in both client app and onesignal servers) and is also flawed if a user does a data clear on Android.

Is there any plans to implement the 2 mentioned methods anytime soon?

**Comment by chmiiller** [comment]
Well with the getTags on iOS you can easily figure it out what tags to delete. For Android I didn't have time to implement yet, and I agree it could be annoying to save it manually on device =/
I will need to use this module on next 2 weeks, so perhaps I can implement them

**Comment by aurusapps** [comment]
@chmiiller  That would be great, thanks. I also recommend to move to the latest SDK version from OneSignal, best to stay updated I think.

PS: I will attempt the code as well over this weekend, will keep you posted on the progress, if I figure it out will share the same...

**Comment by aurusapps** [comment]
@chmiiller I tried using iOS getTags and that seems to fail as well. 
In the sample given in the readme below:

    onesignal.getTags(function(e) {
        if (!e.success) {
            Ti.API.error("Error: " + e.error);
            return
        }

        Ti.API.info(e.results);
    });

Logging e.results gives the value of undefined and Logging the object e results in 
[INFO] :   {
[INFO] :       code = 0;
[INFO] :       success = 1;
[INFO] :   }

**Comment by chmiiller** [comment]
You're right, it's not working =/
The add tag successfully inserts a tag for the user on OneSignal DB, but the GetTags is not working at all...gonna check if possible

**Comment by chmiiller** [comment]
Just got it fixed for iOS! Gonna commit later Today. Basically, the issue was that someone made it on the opposite way 😭, but it happens a lot hahahahaha.
Was:
```
if (error == nil) {
    propertiesDict[@"error"] = [error localizedDescription];
    propertiesDict[@"code"] = NUMINTEGER([error code]);
} else {
    // Are all keys and values Kroll-save? If not, we need a validation utility
    propertiesDict[@"results"] = results ?: @[];
}
```

So, "if we don't have a error (error == null) send the error message"

**Comment by aurusapps** [comment]
hehe, yes thats a funny one. But glad you found a fix easily.
@chmiiller  any thoughts on upping to the latest SDK from onesignal with this fix?

Also, good news is that I was able to implement the GetTags function for Android, will test it and then share the code for you'll to review and include if okay!

**Comment by chmiiller** [comment]
[PR](https://github.com/williamrijksen/com.williamrijksen.onesignal/pull/16) -> getTags fixed and now is also possible to send a notification from the app to another user.
@williamrijksen could you check this PR alstublieft?

**Comment by williamrijksen** [comment]
@aurusapps @chmiiller getTags introduced: https://github.com/williamrijksen/com.williamrijksen.onesignal/releases/tag/1.4.0.
