### ISSUE TITLE
Android Push Notifications do not respect priority

### ISSUE THREAD

**Issue by aurusapps** [williamrijksen/com.williamrijksen.onesignal#17]
I wondered how notifications from some apps draw over a screen and you can read them where as all other notifications only appear as an icon on the status bar.

In my research I found that the priority of the notifications controls this and only priority 10 messages will be shown with a sliding view over other apps or even while on the OS main screen.

However the current module does not support these notifications and do not respect the priority sent. On futher research, I was to realise that Onesignal implemented priority in a later release of their SDK than the one in use in this module.

This issue is therefore a request to use the latest SDK found here:
https://github.com/OneSignal/OneSignal-Android-SDK/blob/b68d7004aaa868b3bdf25b64e4dc5feffcf19d0c/OneSignalSDK.jar

The good news is I have replaced the SDK and tested the priority to be working by simply replace this file and rebuilding the module.

**Comment by chmiiller** [comment]
Nice! Can you do a PR?

**Comment by aurusapps** [comment]
@chmiiller Ok im still learning Github at the moment but Ill create a fork, make my changes and submit a PR include both the SDK upgrade and my implementation of getTags for Android. Ill do this after I make changes on your current version ie. 1.3.1

**Comment by chmiiller** [comment]
Ok, I can help you on that if you want.
Basically: 

1. Fork the repo
2. Clone it on your computer
3. Do your changes
4. Commit your changes
5. Push your commit(s)
6. Open your github forked repo on github website
7. Click on "Pull Requests" on top menu
8. Select "New Pull Request"
9. Wait till Travis check your commit and William have a look at it

BTW, also updated iOS framework on 1.3.1

**Comment by aurusapps** [comment]
@chmiiller 

Thanks and understood, will follow these steps.

Awesome on the iOS Framework upgrade, left a comment on your commit :) really hoping it fixes #13  automatically

**Comment by williamrijksen** [comment]
@aurusapps @chmiiller JAR updated in 1.4.0. Would you verify it's fixed now?

**Comment by chmiiller** [comment]
hey @aurusapps can you check this one and if it is working close this issue?

**Comment by aurusapps** [comment]
working correctly, have tested the following:

- new device registers
- settags
- deletetags
- received and opened handlers of notifications

priority 10 messages working with slide down and draw on other apps 

Its working well!
