### ISSUE TITLE
[iOS] Update OneSignal framework

### ISSUE THREAD

**Issue by chmiiller** [williamrijksen/com.williamrijksen.onesignal#18]
When trying to update module's One Signal framework with the last one on their github repo, the app crashes when I send a notification and app is opened, or attempt to open the app from notification.
The message is:

```
-[TiApp application:didReceiveRemoteNotification:]: unrecognized selector sent to instance 0x1701f0900
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[TiApp application:didReceiveRemoteNotification:]: unrecognized selector sent to instance 0x1701f0900'
```
Not sure what they've changed about it =/
Do you guys have a solution for this by any chance?
Thanks

**Comment by aurusapps** [comment]
Not fully sure but you should check remote notifications settings in your plist file as that was another feature added to one signal SDK probably later than the original SDK used in the module

**Comment by chmiiller** [comment]
I do have the:
```
<key>UIBackgroundModes</key>
    <array>
         <string>remote-notification</string>
         <string>fetch</string>
     </array>
```
On my tiapp.xml, should be enough I think

**Comment by aurusapps** [comment]
Just out of curiosity are you able to replicate the error without liveview on?

**Comment by chmiiller** [comment]
I'm not using liveview at all

**Comment by aurusapps** [comment]
@williamrijksen any ideas on how we can make this work? I think #13 should get auto resolved along with this and we are missing out on sending pictures and videos with notifications on iOS 10+

**Comment by hansemannn** [comment]
The error means that the `didReceiveRemoteNotification:` method cannot be called. Looking into the SDK, it only get's generated when you have the `USE_TI_NETWORKREGISTERFORPUSHNOTIFICATIONS` macro defined, which gets generated during build-time as soon as you use `Ti.Network.registerForPushNotifications`. I hope that helps.

```objc
#ifdef USE_TI_NETWORKREGISTERFORPUSHNOTIFICATIONS
- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo
{
    ...
}
...
#endif
```

**Comment by aurusapps** [comment]
@williamrijksen @chmiiller Any thoughts on @hansemannn input? Ill give it a try if you aren't, just that Im not strong on the iOS skills ...
