### ISSUE TITLE
Notification Received Handler

### ISSUE THREAD

**Issue by chmiiller** [williamrijksen/com.williamrijksen.onesignal#2]
First of all, thanks for the module! It works perfectly!
Do you have any idea on how to listen for the Payload sent together with the Push Notification on the Titanium app?
On Android SDK I've seen this handler `NotificationReceivedHandler`. And for iOS I was wondering if is it possible to use the Titanium callback on the `Ti.Network.registerForPushNotifications()`. Do you think this is gonna work?
I might start implementing the Android version tomorrow, so let me know what do you think =)

**Comment by williamrijksen** [comment]
Hi @chmiiller,

Okay i understand you want to use the additional data you add to a specific notification. Maybe we can use the strategy which has been used in https://github.com/geektimecoil/react-native-onesignal.

On iOS devices i think you can use the `Ti.Network.registerForPushNotifications()` as well, but let me know.

Anyway, feel free to create a new Pull Request, i'll check this as soon as possible.

**Comment by chmiiller** [comment]
Just did it for Android! 🎉
PR: https://github.com/williamrijksen/com.williamrijksen.onesignal/pull/3

**Comment by chmiiller** [comment]
iOS is almost there on the PR as well!

**Comment by williamrijksen** [comment]
Closing in regards to https://github.com/williamrijksen/com.williamrijksen.onesignal/pull/3
