### ISSUE TITLE
OneSignal: OneSignal AppId format is invalid

### ISSUE THREAD

**Issue by shacharudi** [williamrijksen/com.williamrijksen.onesignal#22]
Hi William @williamrijksen ,
Thank you for making this module, it looks great!

I've been trying to integrate it with my appcelerator app on android and been running into this problem described in the title:

I think it's something to do with the way I setup my xml, here's how I set it:

`<meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
			<meta-data android:name="onesignal_app_id" android:value="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" />
			<meta-data android:name="onesignal_google_project_number" android:value="str:xxxxxxxxxxxx" />`

Am I setting this right? Also could you please post an example for the tiapp.xml file?

Thank you!

**Comment by rooterdog** [comment]
I'm having the exact same issue @williamrijksen 
Any help is much appreciated!!!!!

**Comment by williamrijksen** [comment]
You have to replace `android:value="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"` by `android:value="<app id>"` which can be found at One-Signal dashboard -> App Settings -> Keys & IDs.

The google project number can be found after registering you're app at FCM (Firebase Cloud Messaging). Is it clear enough?

**Comment by chmiiller** [comment]
Here are some examples of my app and tiapp.xml configurations.
![ostiappxml](https://cloud.githubusercontent.com/assets/1013632/22549576/41b733e2-e94c-11e6-8815-f87438b637d5.png)

This is my One Signal -> App Settings screen:
![osappsettings](https://cloud.githubusercontent.com/assets/1013632/22549585/4febd3c8-e94c-11e6-8e9b-1075deb341b1.png)

And these are my FCM settings:
![osfcm](https://cloud.githubusercontent.com/assets/1013632/22549592/5ecf874a-e94c-11e6-8011-90bf167ae25b.png)

**Comment by shacharudi** [comment]
Thanks @williamrijksen ! I was missing the `<application>` tag but now it's working great.
And thank you @chmiiller for sharing your XML files, it was very helpful!
Thanks again for making this module, it's awesome!
