### ISSUE TITLE
OneSignal iOS Native 2.4.X Update - NotificationServiceExtension

### ISSUE THREAD

**Issue by jkasten2** [williamrijksen/com.williamrijksen.onesignal#24]
@williamrijksen We recently released version 2.4.0 of our SDK which uses a `NotificationServiceExtension`. Media attachments and action buttons now use a NotificationServiceExtension with mutable-content instead of content-available on iOS 10 for improved delivery reliability and speed. This fixes the issue where notifications with these features would not show if the app was force-quit by swiping it away.
https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/2.4.0

This also includes other bug fixes and improvements so I highly recommend updating. I am OneSignal's lead mobile SDK developer so feel free to ask me any questions if you need any help on updating.

**Update: (2017-03-31)**
2.5.0 has been released with some additional methods, bug fixes and additional improvements.

**Comment by chmiiller** [comment]
Thanks for the information @jkasten2 ! I'm giving it a try but I'm not the module expert here. Gonna let you know if it worked

**Comment by chmiiller** [comment]
hun, not much success here. All I've tried was to update the OneSignal.framework file on Xcode project and module folder. Than rebuilt both module and app and tried to send notifications. I receive the notifications on app three stages: closed, background and foreground but on each case it closes the app when I tapped the notification message (or when it receive it and the app was on foreground).
Is there something special I would need to enable on my info.plist?
For now I only have
```
<key>UIBackgroundModes</key>
	<array>
		<string>remote-notification</string>
		<string>fetch</string>
	</array>
```
Is this enough?
Thanks!

**Comment by jkasten2** [comment]
@chmiiller You will need to add the new target to your Xcode project as well.
[**Add Notification Service Extension**](https://documentation.onesignal.com/docs/ios-sdk-setup#section-1-add-notification-service-extension)

However without it you shouldn't close the app when opening a notification, just won't see custom action buttons or iOS 10 attachments. It is most likely crashing, can you get the full crash log from the device and attach it here?

**Comment by williamrijksen** [comment]
@hansemannn Do you know how to add an " Add Notification Service Extension" in this module? Does Appcelerator support this to integrate into a module?

**Comment by hansemannn** [comment]
@williamrijksen Yes, but not per module but globally per app (makes sense). You would just create a new extension that is linked to the application, see the [Creating iOS Extensions](http://docs.appcelerator.com/platform/latest/#!/guide/Creating_iOS_Extensions_-_Siri_Intents) guide (although using the SiriKit extension, every other extension works the same way).

**Comment by williamrijksen** [comment]
@hansemannn Thanks!

**Comment by williamrijksen** [comment]
Closed: https://github.com/williamrijksen/com.williamrijksen.onesignal/issues/33.
