### ISSUE TITLE
"Location point" empty

### ISSUE THREAD

**Issue by clem983** [williamrijksen/com.williamrijksen.onesignal#25]
Hi,

Thanks for this perfect module !
I just have a question : I'd like to send notifications based on location but the "Location point" column in onesignal is always empty.
How can I do to complete it ?

Thanks a lot :)

**Comment by chmiiller** [comment]
As I can see, we will need to implement promptLocation method on iOS and Android:
https://documentation.onesignal.com/docs/ios-native-sdk#section--promptlocation-

**Comment by williamrijksen** [comment]
@clem983 Yes feel free to create a PR so it's in the module 👍

**Comment by clem983** [comment]
Unfortunately I don't have the skills to do it, for now !
But thanks for your quick answers :)

**Comment by jvandijk** [comment]
@clem983 as a workaround you can use the standard Titanium location permissions. I've they have been given, OneSignal will have access to the location data

**Comment by chmiiller** [comment]
On the latest release version of the module for iOS the option prop `[OneSignal setLocationShared];` is set to *YES* and it indeed works giving the location to the user in One Signal's Audience interface. Gonna close this issue for now, please feel free to open another one in case this is not working on Android.
Thanks!
