### ISSUE TITLE
Missing libraries

### ISSUE THREAD

**Issue by lukadavi** [williamrijksen/com.williamrijksen.onesignal#26]
Hi,
i got this error compiling for ios and for android as well.
I'm using titanium 6.0.3.

I know i'm doing something wrong but i don't know what.

IOS
`[ERROR] :  Module com.williamrijksen.onesignal version 1.5.0 is missing library file: /Users/alessandrofranchini/Library/Application Support/Titanium/modules/iphone/com.williamrijksen.onesignal/1.5/libcom.williamrijksen.onesignal.a`
ANDROID
`[ERROR] :  art: dlopen("/data/app/it.genomedics.rivistamedia-1/lib/arm/libcom.mykingdom.mupdf.so", RTLD_LAZY) failed: dlopen failed: could not load library "libstlport_shared.so" needed by "libcom.mykingdom.mupdf.so"; caused by library "libstlport_shared.so" not found
[ERROR] :  TiApplication: (KrollRuntimeThread) [88,600] Sending event: exception on thread: KrollRuntimeThread msg:java.lang.UnsatisfiedLinkError: dlopen failed: could not load library "libstlport_shared.so" needed by "libcom.mykingdom.mupdf.so"; caused by library "libstlport_shared.so" not found; Titanium 6.0.3,2017/03/22 12:00,undefined
[ERROR] :  TiApplication: java.lang.UnsatisfiedLinkError: dlopen failed: could not load library "libstlport_shared.so" needed by "libcom.mykingdom.mupdf.so"; caused by library "libstlport_shared.so" not found
[ERROR] :  TiApplication: 	at java.lang.Runtime.loadLibrary(Runtime.java:371)
[ERROR] :  TiApplication: 	at java.lang.System.loadLibrary(System.java:989)
[ERROR] :  TiApplication: 	at org.appcelerator.kroll.runtime.v8.V8Runtime.loadExternalModules(V8Runtime.java:151)
[ERROR] :  TiApplication: 	at org.appcelerator.kroll.runtime.v8.V8Runtime.initRuntime(V8Runtime.java:118)
[ERROR] :  TiApplication: 	at org.appcelerator.kroll.KrollRuntime.doInit(KrollRuntime.java:205)
[ERROR] :  TiApplication: 	at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:114)
[ERROR] :  AndroidRuntime: FATAL EXCEPTION: KrollRuntimeThread
[ERROR] :  AndroidRuntime: Process: it.genomedics.rivistamedia, PID: 18023
[ERROR] :  AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: could not load library "libstlport_shared.so" needed by "libcom.mykingdom.mupdf.so"; caused by library "libstlport_shared.so" not found
[ERROR] :  AndroidRuntime: 	at java.lang.Runtime.loadLibrary(Runtime.java:371)
[ERROR] :  AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:989)
[ERROR] :  AndroidRuntime: 	at org.appcelerator.kroll.runtime.v8.V8Runtime.loadExternalModules(V8Runtime.java:151)
[ERROR] :  AndroidRuntime: 	at org.appcelerator.kroll.runtime.v8.V8Runtime.initRuntime(V8Runtime.java:118)
[ERROR] :  AndroidRuntime: 	at org.appcelerator.kroll.KrollRuntime.doInit(KrollRuntime.java:205)
[ERROR] :  AndroidRuntime: 	at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:114)`

**Comment by chmiiller** [comment]
Where did you get the module from? I recommend you take it from here: https://github.com/williamrijksen/com.williamrijksen.onesignal/releases
If you are trying to build it by yourself for iOS, seems that the `OneSignal.framework` file is missing in your XCode project.

**Comment by williamrijksen** [comment]
What's the version you described in your tiapp.xml? 1.5 or 1.5.0? 1.5.0 is required.

**Comment by lukadavi** [comment]
Thank you William.
I was trying to build it by myself. Now I downloaded the modules from [https://github.com/williamrijksen/com.williamrijksen.onesignal/releases](https://github.com/williamrijksen/com.williamrijksen.onesignal/releases)
and it works fine
;)
