### ISSUE TITLE
onesignal.idsAvailable For Android

### ISSUE THREAD

**Issue by santhoshvkumar** [williamrijksen/com.williamrijksen.onesignal#27]
What's the way to receive the `playerID` for OneSignal in Android. My Scenario is, wanted to send Push Notification to each and every user from the REST API Call with out PlayerID how to Achieve it ?

**Comment by chmiiller** [comment]
Hi @santhoshvkumar I've implemented it for iOS only. You can have a look on how I did it and try it by yourself. It is not so complicated I think.
