### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by AppWerft** [williamrijksen/com.williamrijksen.onesignal#31]
is it possible to rename this repo into _Ti.OneSignal_ (for better finding of it)?

**Comment by williamrijksen** [comment]
@AppWerft This repo is linked by Onesignal in their docs, so I don't see any reason to rename this module.

**Comment by AppWerft** [comment]
OK in this case … Maybe you write the text "Ti.Onesignal" in your README for better finding.
