### ISSUE TITLE
Warnings in onesignal event

### ISSUE THREAD

**Issue by ottopic** [williamrijksen/com.williamrijksen.onesignal#35]
When I use my objects for example inside onesignal.idsAvailable(function(e) {}); I receive many warning and relative errors that I'm creating a object in differente context than the calling function, for example:

Creating [object TiDatabase] in a different context than the calling function
Creating [object TiAppProperties] in a different context than the calling function

How can be fixed?
I have read that can be a problem between js and objective-c ... http://noodlecode.net/2016/08/creating-object-in-a-different-context-than-the-calling-function/

**Comment by williamrijksen** [comment]
@ottopic This is about the idsAvailable in the iOS module, right? The idsAvailable is deprecated and should being replaced by OSPermissionSubscriptionState. See https://stackoverflow.com/a/43240950

**Comment by chmiiller** [comment]
Latest release of the iOS module removes this method implementation and from header. You shouldn't see these warning anymore.
