### ISSUE TITLE
Compiled Modules

### ISSUE THREAD

**Issue by CJ-Oodle** [williamrijksen/com.williamrijksen.onesignal#36]
Is there any chance we could get compiled modules added to the repo? I have been having all sorts of issues compiling these repositories based on versions of node and my android ndk in particular.
As an example on the android compile:
[ERROR] /Users/carmin/Library/Application Support/Titanium/mobilesdk/osx/6.1.0.GA/android/native/include/AndroidUtil.h:57:49: warning: format specifies type 'int' but the argument has type 'long' [-Wformat]

**Comment by williamrijksen** [comment]
@CJ-Oodle You can find the releases here: https://github.com/williamrijksen/com.williamrijksen.onesignal/releases

**Comment by CJ-Oodle** [comment]
Thanks William, I was making that way harder than it needed to be!
