### ISSUE TITLE
The application has crashed with an uncaught exception 'NSInvalidArgumentException'.

### ISSUE THREAD

**Issue by Born2Debug** [williamrijksen/com.williamrijksen.onesignal#39]
Hello, I have an issue using Titanium SDK 6.1.1GA.

Here's the complete error.

`The application has crashed with an uncaught exception 'NSInvalidArgumentException'.
[ERROR] :  Reason:
[ERROR] :  -[ComWilliamrijksenOnesignalModule application:didFailToRegisterForRemoteNotificationsWithError:]: unrecognized selector sent to instance 0x7faecb7166b0
[ERROR] :  Stack trace:
[ERROR] :  0   CoreFoundation                      0x0000000117392af3 __exceptionPreprocess + 147
[ERROR] :  1   libobjc.A.dylib                     0x0000000116950141 objc_exception_throw + 48
[ERROR] :  2   CoreFoundation                      0x0000000117402134 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
[ERROR] :  3   CoreFoundation                      0x0000000117319840 ___forwarding___ + 1024
[ERROR] :  4   CoreFoundation                      0x00000001173193b8 _CF_forwarding_prep_0 + 120
[ERROR] :  5   Surveiyo                            0x000000010faefa33 -[TiApp application:didFailToRegisterForRemoteNotificationsWithError:] + 99
[ERROR] :  6   Surveiyo                            0x000000010fc5f3fb -[OneSignalAppDelegate oneSignalDidFailRegisterForRemoteNotification:error:] + 251
[ERROR] :  7   libdispatch.dylib                   0x000000011a057585 _dispatch_call_block_and_release + 12
[ERROR] :  8   libdispatch.dylib                   0x000000011a078792 _dispatch_client_callout + 8
[ERROR] :  9   libdispatch.dylib                   0x000000011a060247 _dispatch_main_queue_callback_4CF + 1041
[ERROR] :  10  CoreFoundation                      0x0000000117357909 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
[ERROR] :  11  CoreFoundation                      0x000000011731dae4 __CFRunLoopRun + 2164
[ERROR] :  12  CoreFoundation                      0x000000011731d016 CFRunLoopRunSpecific + 406
[ERROR] :  13  GraphicsServices                    0x0000000119e0ca24 GSEventRunModal + 62
[ERROR] :  14  UIKit                               0x00000001128cf134 UIApplicationMain + 159
[ERROR] :  15  Surveiyo                            0x000000010f909e64 main + 100
[ERROR] :  16  libdyld.dylib                       0x000000011a0c165d start + 1
[ERROR] :  17  ???                                 0x0000000000000001 0x0 + 1
-- End simulator log ---------------------------------------------------------`

**Comment by williamrijksen** [comment]
@Born2Debug Did you check https://github.com/williamrijksen/com.williamrijksen.onesignal/pull/38#discussion_r130996351?

**Comment by hansemannn** [comment]
The error ineicates that the UIApplication delegate you are calling is nil at this point. It could be related, but could also be an issue with not nil-checking it before calling. Did this not occur with 6.0.x and 5.5.x? This is very important to know

**Comment by jvandijk** [comment]
@Born2Debug can you test this with version 1.7.0?

**Comment by Born2Debug** [comment]
@jvandijk it works fine with 1.7.0 ;) Thanks so much. Good work guys.

**Comment by jvandijk** [comment]
Thanks for the heads up!
