### ISSUE TITLE
android notification icons

### ISSUE THREAD

**Issue by rooterdog** [williamrijksen/com.williamrijksen.onesignal#40]
I cant seem to get anything other then the standard "bell" icon to show up in notifications. Is this supported? If so how are others getting it to work? I've tried adding to resources, etc...
BTW, guess this is not an "issue" but be great if it worked.. probably just something I'm not doing correctly...

**Comment by jvandijk** [comment]
The naming convention is hardcoded, it should be `ic_stat_onesignal_default.png`. See the OneSignal documentation for more details: https://documentation.onesignal.com/docs/customize-notification-icons

**Comment by rooterdog** [comment]
thats exactly what I did, but wouldnt work.. perhaps I put in wrong directory...
I placed in app>assets>android>images>drawable-hdpi,drawable-hmpi, etc

**Comment by jvandijk** [comment]
The files should be placed in `app/platform/res/drawable-{hdpi,mdpi,xhdpi,xxhdpi,xxxhdpi}`

**Comment by rooterdog** [comment]
that did it....

actually had to add "android" to it, but working now...
app/platform/android/res/drawable-{hdpi,mdpi,xhdpi,xxhdpi,xxxhdpi}
Thank you for the help!
