### ISSUE TITLE
Not compatible with Ti SDK 6.1.x.GA+

### ISSUE THREAD

**Issue by clemblanco** [williamrijksen/com.williamrijksen.onesignal#45]
As soon as I try to to use this module with a Ti SDK version higher than 6.0.x.GA my application crashes.

**Comment by williamrijksen** [comment]
@Claymm Thank you for reporting this issue. Could you add the platform (android/iOS) and the crashlog into this issue? When is this crash occurring?

**Comment by jvandijk** [comment]
@Claymm could you retry the 1.7.1 release? I've rebuilt it, because it seemed that the dist was different from what I expected it to be.

**Comment by AshKernsworth** [comment]
I'm working with @Claymm, I just updated it and it works great.
Thanks @williamrijksen & @jvandijk

**Comment by jvandijk** [comment]
Thanks for the heads up!
