### ISSUE TITLE
Google Play Services error

### ISSUE THREAD

**Issue by ulissesrsilva** [williamrijksen/com.williamrijksen.onesignal#47]
Hey everyone!

I'm trying to use One Signal in my app but i'm facing this error:

`build/android/AndroidManifest.xml:20: error: Error: No resource found that matches the given name (at 'value' with value '@integer/google_play_services_version').`

I've tried with (and without) `<meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version"/> `inside the application tag.

Has anyone had this error too? I'm using SDK 6.1.1 GA, but I got the same error with every 6.0.x version. What am I doing wrong? =/

Thanks!!

**Comment by jvandijk** [comment]
@ulissesrsilva I've just re-uploaded the 1.7.1 version dist in the releases. Could you test that one?

**Comment by ulissesrsilva** [comment]
@jvandijk I've tested and the same error happened =/

**Comment by jvandijk** [comment]
Damnit... the build is still incorrect indeed.

**Comment by ulissesrsilva** [comment]
I have zero experience building modules, but is there something I can do to help?

**Comment by jvandijk** [comment]
@ulissesrsilva the module is now updated again. And now it for sure has the expected content. Could you verify?

**Comment by ulissesrsilva** [comment]
YEEEEEEEEEEES! It worked! Your module is great man!!
Thank you so much o/
