### ISSUE TITLE
Incompatibility with Ti.GA module

### ISSUE THREAD

**Issue by clemblanco** [williamrijksen/com.williamrijksen.onesignal#48]
Hi, I'm getting an incompatibility issue with [benbahrenburg/Ti.GA](https://github.com/benbahrenburg/Ti.GA) around `google-play-services-base.jar`.

Both modules use the same jar file.

I've tried copying it from one module to the other one (both ways) but it didn't do the trick, I still get an error upon dexer translation when trying to compile for Android using 6.2.2.GA Ti SDK.

Anyway you can help solving this issue?

I've found some leads [here](https://jira.appcelerator.org/browse/AC-4707), [there](https://jira.appcelerator.org/browse/AC-4708) and [here](https://jira.appcelerator.org/browse/TIMOB-24722).

**Comment by jvandijk** [comment]
In the README we've described how you're able to resolve this issue by manually changing google play services versions.

But here's attached a zip that should work with 1.7.1
[ti.ga.zip](https://github.com/williamrijksen/com.williamrijksen.onesignal/files/1357292/ti.ga.zip)

**Comment by clemblanco** [comment]
Thanks a bunch, I'll give it a spin! 👍

**Comment by clemblanco** [comment]
I can compile now, thanks a lot! #hero
