### ISSUE TITLE
Is there any compatible version for 6.0.0.GA sdk 23 ...

### ISSUE THREAD

**Issue by pburel** [williamrijksen/com.williamrijksen.onesignal#5]
Is there any compatible version for 6.0.0.GA sdk 23 ...

**Comment by williamrijksen** [comment]
@pburel Did you try https://github.com/williamrijksen/com.williamrijksen.onesignal/releases/tag/1.2.1?

This version is builded with Titanium 6 and SDK 23:
```
titanium.platform=/Users/travis/Library/Application Support/Titanium/mobilesdk/osx/6.1.0.v20161205180708/android
android.platform=/Users/travis/Library/Application Support/Titanium/sdks/android-sdk-macosx/platforms/android-23
```

**Comment by williamrijksen** [comment]
@pburel Closing in regards to: https://github.com/williamrijksen/com.williamrijksen.onesignal/pull/8.

**Comment by chmiiller** [comment]
We did a new version supporting 6.0.0.GA as a Xmas gift for you 🎉⛄️
release 1.3.0 can be used with the new Ti SDK:
https://github.com/williamrijksen/com.williamrijksen.onesignal/releases/tag/1.3.0
