### ISSUE TITLE
Runtime disposed, cannot fire event 'notificationReceived'

### ISSUE THREAD

**Issue by ManasMack** [williamrijksen/com.williamrijksen.onesignal#53]
Facing "Runtime disposed, cannot fire event 'notificationReceived'" 
and "Runtime disposed, cannot fire event 'notificationOpened'"

On android device while app is not running(In background) both the notificationReceived & notificationOpened 
method does not works
Titanium SDK : 6.2.2.GA

**Comment by jvandijk** [comment]
Release 2.0.0 resolves this issue. It does require TItanium SDK 7.x though
