### ISSUE TITLE
Issue with Android??

### ISSUE THREAD

**Issue by arbindbhagat** [williamrijksen/com.williamrijksen.onesignal#56]
I am not sure if this is an issue, or am I doing something wrong? Below is the screenshot. It is working for iOS, but for android, the module is just not being recognized. Please advise.
http://prntscr.com/i3c47t

**Comment by noxgeneration** [comment]
I have the same problem. What is wrong? 

I'm using Titanium SDK 7.0.1

**Comment by chmiiller** [comment]
This means that you're trying to use the module in a project with a newer Titanium SDK than the app was built with. If I'm not mistaken the module is not ready for Titanium SDK 7.x yet.

**Comment by jvandijk** [comment]
Version 2.0.0 has just been released. Travis is building the distributable, which will become available under releases.
