### ISSUE TITLE
"notificationOpened" and "notificationReceived" not firing

### ISSUE THREAD

**Issue by deckameron** [williamrijksen/com.williamrijksen.onesignal#59]
I am testing on a iPhone 6S, iOS 10.3.3, Titanium SDK 6.3.0 and module 1.7.1.

I can read the logs but the events never get fired.

When I receive the notification when the app is opened, it prompts an alert. Why?

**Comment by philcandel** [comment]
Hello

I have the same issue... using  iOS 12.0, Titanium SDK 7.4.0 and module 2.0.1.

I know it is hard to maintain,
Do you have any idea when it will be solved ? 

Thanks for all your work

**Comment by jvandijk** [comment]
Register the listeners as early as possible, preferable in alloy.js and use the latest release : https://github.com/williamrijksen/com.williamrijksen.onesignal/releases/tag/2.1.0
