### ISSUE TITLE
Android Issue

### ISSUE THREAD

**Issue by arbindbhagat** [williamrijksen/com.williamrijksen.onesignal#61]
I am using the recent version (2.0.0) as well as ti.playservices module. My one_signal_app_id is also correct. However, I am getting the following error.

[ERROR] :  OneSignal: OneSignal AppId format is invalid.
[ERROR] :  OneSignal: Example: 'b2f7f966-d8cc-11e4-bed1-df8f05be55ba'
[ERROR] :  OneSignal:
[ERROR] :  OneSignal: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
[ERROR] :  OneSignal: 	at java.util.UUID.fromString(UUID.java:192)
[ERROR] :  OneSignal: 	at com.onesignal.OSUtils.initializationChecker(OSUtils.java:62)
[ERROR] :  OneSignal: 	at com.onesignal.OneSignal.init(OneSignal.java:491)
[ERROR] :  OneSignal: 	at com.onesignal.OneSignal.init(OneSignal.java:467)
[ERROR] :  OneSignal: 	at com.onesignal.OneSignal.access$000(OneSignal.java:79)
[ERROR] :  OneSignal: 	at com.onesignal.OneSignal$Builder.init(OneSignal.java:283)
[ERROR] :  OneSignal: 	at com.williamrijksen.onesignal.ComWilliamrijksenOnesignalModule.onAppCreate(ComWilliamrijksenOnesignalModule.java:65)
[ERROR] :  OneSignal: 	at java.lang.reflect.Method.invoke(Native Method)
[ERROR] :  OneSignal: 	at com.appsconda.onesignal.OneSignalApplication.onCreate(OneSignalApplication.java:151)
[ERROR] :  OneSignal: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
[ERROR] :  OneSignal: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5403)
[ERROR] :  OneSignal: 	at android.app.ActivityThread.-wrap2(ActivityThread.java)
[ERROR] :  OneSignal: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
[ERROR] :  OneSignal: 	at android.os.Handler.dispatchMessage(Handler.java:102)
[ERROR] :  OneSignal: 	at android.os.Looper.loop(Looper.java:154)
[ERROR] :  OneSignal: 	at android.app.ActivityThread.main(ActivityThread.java:6119)
[ERROR] :  OneSignal: 	at java.lang.reflect.Method.invoke(Native Method)
[ERROR] :  OneSignal: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
[ERROR] :  OneSignal: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by jvandijk** [comment]
Could you share a part of the tiapp.xml? Because the error states that the format of the ID is incorrect.

**Comment by arbindbhagat** [comment]
<img width="957" alt="screenshot at feb 12 21-36-11" src="https://user-images.githubusercontent.com/19579469/36118287-c3d43d58-103c-11e8-80b1-2deaadf392cb.png">
Here is the screenshot of the tiapp.xml .

**Comment by jvandijk** [comment]
The metadata should be embedded under android > manifest > application > meta-data to work

**Comment by williamrijksen** [comment]
@arbindbhagat Can you confirm this issue can be closed?

**Comment by arbindbhagat** [comment]
@williamrijksen Yes, that issue is now fixed.
However, while following the instructions mentioned in the documentation section of this github project, the notification for android is being received only when the app is opened. The notification is not being received when the app is closed.

Is this supposed to be working this way?

**Comment by chmiiller** [comment]
Hi @arbindbhagat .
I'm using the newest version and the notification is being received successfully when the app is also closed.
@williamrijksen I think his question has been answered and you can close this issue then =)

**Comment by jvandijk** [comment]
Thanks for confirming @chmiiller
