### ISSUE TITLE
inFocusDisplaying

### ISSUE THREAD

**Issue by emmanuelfrancis** [williamrijksen/com.williamrijksen.onesignal#65]
I tried setting below but I still get message alert when app is in foreground. Please let me know how to suppress notification alert message when app is in foreground.
var onesignal = require('com.williamrijksen.onesignal');
onesignal.inFocusDisplaying = onesignal.Notification;

**Comment by emmanuelfrancis** [comment]
This seems to be working with new version 2.0.1

**Comment by jvandijk** [comment]
Thanks for confirming! Closing now
