### ISSUE TITLE
10 Android SDK releases --is this module maintained ?

### ISSUE THREAD

**Issue by adriendillens** [williamrijksen/com.williamrijksen.onesignal#72]
Hi @williamrijksen @chmiiller @jvandijk @Topener @aduptoro & all !

One time again, thanks for this module.

I'm facing issues on Android 8 devices : push notifications (app killed & app in background) are not received.

Last commit of this module is 25 March 2018 (6 months ago)
10 new Android SDK versions have been released during this time
https://github.com/OneSignal/OneSignal-Android-SDK/releases

So, it's not clear about is this module maintained ?
Otherwise, just explain it in readme because production apps really suffer !
Opened issues didn't receive answers since few months ...

A quick answer will be really appreciated guys

If i can update onesignal Android SDK myself, please list me the steps (but i think java code must be changed ?).

**Comment by jordansilva** [comment]
Hi,

The last version released on 26th March was using OneSignal version 3.8.0 as you can see here:
https://github.com/williamrijksen/com.williamrijksen.onesignal/releases

I'm getting current branches and updating the OneSignal module on Android to the version 3.10.0. I'm going to do a PR this week with this updates.

**Comment by chmiiller** [comment]
Besides @jordansilva 's work, I'm updating the iOS library version also this week!

**Comment by adriendillens** [comment]
Oh nice guys !

I really appreciate your quick replies.

If i can help for something, just tell me!

Good job, thanks a lot 👍 👍 👍

**Comment by adriendillens** [comment]
@jordansilva I found something interesting

in this Android SDK issue https://github.com/OneSignal/OneSignal-Android-SDK/issues/337
they are talking about android.permission.BIND_JOB_SERVICE to enable
I don't know if it's needed but ... Maybe this can helps you ;-)

**Comment by jvandijk** [comment]
@adriendillens @jordansilva that was already addressed in the latest release. Check the changes that were made to the timodule.xml

**Comment by jordansilva** [comment]
@jvandijk is in the March release that I referred before, right?
On my side, I'm just updating the SDK to 3.10.0, merged fix branches that were ahead of the master branch, and I'm testing on my project now. Everything seems good until now.  👍

**Comment by jvandijk** [comment]
@jordansilva yes those were in the 2.0.1 release from March

**Comment by jordansilva** [comment]
@jvandijk @chmiiller 
I'm planning to merge @williamrijksen branches:
- fix/deprecation-ids-available;
- upgrade/onesignal-sdk;
- introduce-subscription-listeners;
- introduce-permission-listeners;
- clear-notifications; 

check if everything is ok and submit a pull request what do you think? or should I wait for @williamrijksen?

**Comment by jvandijk** [comment]
@jordansilva the upgrade/onesignal-sdk branch will likely break the iOS version. This module overrides a mapping structure from the OneSignal module SDK which changed between releases. This needs validation before merging that.

**Comment by jvandijk** [comment]
A new release is available : https://github.com/williamrijksen/com.williamrijksen.onesignal/releases/tag/2.1.0
