### ISSUE TITLE
Ti SDK 7.4.0 Support - iOS

### ISSUE THREAD

**Issue by joshualambert** [williamrijksen/com.williamrijksen.onesignal#75]
Greetings,

If you use the current release version of this module with the latest Titanium SDK (7.4.0.GA), you can consistently see the following crash:

1.) Start your app.
2.) Register for push notifications.
3.) Kill your app. (Double-tap home button, swipe up on app.)
4.) Send push notification from oneSignal.
5.) Open push notification on your device.
6.) You'll see the app splashscreen, then the app will immediately crash. No hints in the terminal.

If you send the push notification while the app is running, everything works as intended.

iOS12 reliability depends on fixes present in TiSDK 7.4.0. In order to use OneSignal, I had to manually merge in the iOS12 fixes from 7.4.0.GA into 7.2.0.GA, the last TiSDK that OneSignal runs on without crashing. Something broke from 7.3.0GA and on.

**Comment by SquirrelMobile** [comment]
+1

**Comment by joshualambert** [comment]
Bump! Really need this updated so I can use the latest TiSDK. I am a paying OneSignal customer. Any help would be significantly appreciated.

**Comment by fabiomlferreira** [comment]
I have exactly the same problem. Please can someone fix this?

**Comment by janvennemann** [comment]
Can you provide a crash report?

**Comment by joshualambert** [comment]
@janvennemann I have emailed this to you now.

**Comment by alexakass** [comment]
+1

**Comment by alexakass** [comment]
Any news on this as? 1 month for a serious issue to be resolved is worrying.

**Comment by SquirrelMobile** [comment]
+1

**Comment by joshualambert** [comment]
Please try testing with this build and let me know how it goes: https://playground.smalltownhosting.com/com.williamrijksen.onesignal.zip

This includes the changes from the PR currently open here:
https://github.com/williamrijksen/com.williamrijksen.onesignal/pull/62

**Comment by joshualambert** [comment]
@williamrijksen has added me as a collaborator on this repo. If we can certify the changes he's added behave correctly, we can merge this and update the repo.

**Comment by williamrijksen** [comment]
Good job @joshualambert !

**Comment by joshualambert** [comment]
OK so we're seeing a problem with the above build based on PR #62. The data payloads are coming in blank that we use for push-based app deeplinking. Unsure why they're blank at this point.

**Comment by Melonbwead** [comment]
Hey hey, Is there any update on this, been using the Titanium 7.4.1 SDK and we are seeing crashes on open push notification on your device.

**Comment by SquirrelMobile** [comment]
The app crash when opening a push notification, @williamrijksen can you create a release please if this commit fix the problem ?

**Comment by danimarin** [comment]
+1

**Comment by joe-f** [comment]
+1 @janvennemann Any ideas on how to move this issue forward?

**Comment by janvennemann** [comment]
#77 was merged recently which fixed the issue and i think @jvandijk is currently preparing a new release.

**Comment by danimarin** [comment]
Please, this bug is critical for some customers that pay for OneSignal. How could we help to release a new version faster?

**Comment by janvennemann** [comment]
To temporarily unblock you i've drafted a pre-release from the current master branch: https://www.dropbox.com/s/pel2y5c9h9do9h0/com.williamrijksen.onesignal-iphone-2.0.1.zip?dl=0

**Comment by jvandijk** [comment]
The release is now done : https://github.com/williamrijksen/com.williamrijksen.onesignal/releases/tag/2.1.0

Be aware, this is an open source module. The maintainers of this module are in no way affiliated with OneSignal!
