### ISSUE TITLE
External User Id

### ISSUE THREAD

**Issue by clem983** [williamrijksen/com.williamrijksen.onesignal#80]
Hi,

Thank you for this module :)

I'd like to know if it's possible to send the "external user id" parameter to onesignal, in order to target a list of users by their ID ?
If not, how can I send a notification to a list of users ?
I don't find any information about this.

Thanks a lot :)

**Comment by jvandijk** [comment]
Since the latest OneSignal SDK's in version 2.1.1 this is possible, but not in this implementation yet. You'll have to expose the setExternalUserId method to be able to send this information.

If you create a PR for this, I'll be happy to merge and release this.

**Comment by joshualambert** [comment]
@clem983 Did you ever implement the "setExternalUserId" method?

**Comment by clem983** [comment]
Unfortunately, no :/

**Comment by deckameron** [comment]
@clem983 @jvandijk I have [implemented it](https://github.com/deckameron/Ti.Android.Onesignal) in case you still need it.

**Comment by chmiiller** [comment]
Yo @deckameron any plans on opening a PR for this?

**Comment by chmiiller** [comment]
Hi everyone, I've just published an iOS release where `setExternalUserId` and `removeExternalUserId` are implemented. As my project will also need an Android implementation, that's my next task. You can take the new iOS version here: https://github.com/williamrijksen/com.williamrijksen.onesignal/releases/tag/2.2.1

**Comment by chmiiller** [comment]
There are 2 new releases on this repo https://github.com/williamrijksen/com.williamrijksen.onesignal/releases/tag/2.1.2 on Android and https://github.com/williamrijksen/com.williamrijksen.onesignal/releases/tag/2.2.2 on iOS.
Both versions now support setting and removing externalUserId
