### ISSUE TITLE
URGENT & IMPORT iOS 13 Update Changes

### ISSUE THREAD

**Issue by wawebtech** [williamrijksen/com.williamrijksen.onesignal#85]
**Does the following message effect the latest sdk in release here? i'm using titanium sdk 7.4 & xcode 10**

===========================
Hi there,

Due to a change that may occur as part of the upcoming iOS 13 release, you must update to the latest version of the iOS SDK before building your app with Xcode 11. All of OneSignal’s wrapper SDKs including React Native, Unity, and Flutter have been updated as well.

The reason for this is that Xcode 11, which is being released alongside iOS 13, breaks a common technique that apps and libraries like OneSignal were using to get a push token for the device. If you do not use our new SDK then new users will not be able to subscribe to notifications from your app.

This unannounced Xcode change was identified by the OneSignal team as part of our process of thoroughly testing all beta releases of iOS prior to their public launch. As soon as we became aware, we filed a bug report with Apple and updated our SDKs to ensure guarantee ongoing compatibility. By updating the SDK before your next app release, there will be no impact to your app or subscribers.

Thank you for using OneSignal and our team is available if you have any questions about this.

Best regards,
OneSignal Team

**Comment by chmiiller** [comment]
I think that it only affects those building their apps with Xcode 11. If you stay on Xcode 10 and the old library it's ok. But I couldn't find something to be 100% sure about it.
We need that someone updates the SDK ASAP, since now Apple is rejecting apps with UIWebView and this version of the SDK is still using it: https://github.com/OneSignal/OneSignal-iOS-SDK/issues/522

**Comment by chmiiller** [comment]
From release 2.2.0 I have this fixed. PR #88 is the one taking care of all these updates.
