### ISSUE TITLE
Current module v2.1.1 is not working with TI SDK 8.2.1.GA. Help Needed

### ISSUE THREAD

**Issue by MotiurRahman** [williamrijksen/com.williamrijksen.onesignal#87]
I can build App with this module version but App is not subscribed to the dashboard. Here is the attached image. Could you please update this module with the latest Ti SDK
![Screenshot 2019-12-15 at 7 08 46 AM](https://user-images.githubusercontent.com/5361753/70857071-6a35bb00-1f12-11ea-941b-e0233ff21c83.png)
However, I do not use any other push SDK or push related code.

**Comment by frodfigu** [comment]
Me too.

**Comment by deckameron** [comment]
I have experienced this issue before. 
The only way I got it working was creating my Push Certificates again. I started it from scratch and it worked just fine.

**Comment by MaianaBt** [comment]
any news about this?

**Comment by chmiiller** [comment]
It should be working now guys. PR #88 fixes a bunch of stuff and I've tested it a lot and everything seems fine. Let's close this issue now and please feel free to open any other if you have a question. (I'm also available on TiSlack)
