### ISSUE TITLE
Notification clicked: Android issue 2373 detected (missing intent CATEGORY_LAUNCHER or FLAG_ACTIVITY_RESET_TASK_IF_NEEDED)

### ISSUE THREAD

**Issue by pburel** [williamrijksen/com.williamrijksen.onesignal#9]
correction context: SDK 6.0.0.GA, Huawei VNS-L31, android 6.0 EMUI 4.1
TiApp.xml: add ->
`<property name="ti.android.bug2373.finishfalseroot" type="bool">true</property>`

**Comment by chmiiller** [comment]
Have a look at this: https://github.com/dbankier/TiShadow/issues/379
Not so elegant, but can you please tell me if it solves your problem?

**Comment by aurusapps** [comment]
The work around offered worked for me

**Comment by williamrijksen** [comment]
Workaround is not necessary anymore because of the merging of #32.
