### ISSUE TITLE
getTags returns wrong tags of current player

### ISSUE THREAD

**Issue by frodfigu** [williamrijksen/com.williamrijksen.onesignal#93]
When I´m call onesignal.getTags... the returned data is wrong... Not the correct tags for current user.

In Onesignal console can I view the correct tags and doesn´t match with the returned from this module.

Any solution?

**Comment by chmiiller** [comment]
Is this on iOS or Android? I've just tested it on iOS and it is working fine. Don't forget that getTags receives a callback function with a result as a parameter where the user tags are, for example:
```
onesignal.getTags(function(res){
        console.log(res);
        // You will get something like this:
        // {
        //     "success": true,
        //     "results": {
        //         "my_tag": "my_value"
        //     }
        // }
    });
```

**Comment by chmiiller** [comment]
Ok just tested it out on Android with the same snippet from above and the result is the same. Closing this issue.
